### ISSUE TITLE
Revolt API 0.5.3 support.

### ISSUE THREAD

**Issue by insertish** [5elenay/revoltgo#3]
Since your library uses user authentication, you need to update certain routes. (https://github.com/revoltchat/delta/issues/63)

Revolt's user authentication flow has been overhauled, changes include:
- Completely re-done REST API.
- Deprecation of `x-user-id` header.

Documentation is available here: https://developers.revolt.chat/api/#tag/Account

**Comment by 5elenay** [comment]
Will be updated soon as possible.
