### ISSUE TITLE
Revolt server for Revoltgo

### ISSUE THREAD

**Issue by ayntgl** [5elenay/revoltgo#4]
Hey there! I figured it would be a good idea to create a centralized server for Revolt API-related projects, so I created a new server for Revolt API libraries. What are your thoughts on being part of the server and having a custom channel for Revoltgo? Let me know what you think 😃

Revolt API server: https://rvlt.gg/4GcFZtdA

**Comment by 5elenay** [comment]
Excellent idea! I joined to the server with my account `@abcdef`. 
Also sorry for the late response, I'm too busy with my school.
