### ISSUE TITLE
Bot goes offline after a few hours

### ISSUE THREAD

**Issue by elainaaa** [5elenay/revoltgo#7]
Hello, lately ive noticed my bot turning off randomly a few hours after startup and when i checked the logs nothing seemed to be wrong. Could it be that the client session or whatever times out after a few hours?
Edit: it seems like it happens if the bot is inactive/unused for a few hours. I tried using the bot once every hour and it managed to stay online until now

**Comment by 5elenay** [comment]
Sorry for the late response, I will check the websocket connection myself for see the problem. I will reply back when i found the issue.

**Comment by 5elenay** [comment]
Can you reply back if your problem is solved or not?

**Comment by elainaaa** [comment]
It seems to be fixed but i am not sure if this is supposed to happen but it logs every event now
![image](https://user-images.githubusercontent.com/58641892/151610346-a711690c-1236-4de2-a6bf-e333a6a6f4ab.png)

**Comment by 5elenay** [comment]
> It seems to be fixed but i am not sure if this is supposed to happen but it logs every event now ![image](https://user-images.githubusercontent.com/58641892/151610346-a711690c-1236-4de2-a6bf-e333a6a6f4ab.png)

Yep i forgot to delete the print act like its a feature xd.

**Comment by elainaaa** [comment]
> > It seems to be fixed but i am not sure if this is supposed to happen but it logs every event now ![image](https://user-images.githubusercontent.com/58641892/151610346-a711690c-1236-4de2-a6bf-e333a6a6f4ab.png)
> 
> Yep i forgot to delete the print act like its a feature xd.

Alright, thanks for fixing the main problem though 👍
